# Generated by Django 4.2.7 on 2023-11-24 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_backup', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_marca', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('name_equipo', models.CharField(max_length=255)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='proyecto.marca')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('registro', models.TextField()),
                ('contenido', models.FileField(upload_to='respaldos/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proyecto.equipo')),
            ],
        ),
    ]
