# Generated by Django 4.2.7 on 2023-11-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_backup',
            name='status',
            field=models.IntegerField(choices=[[0, 'Respaldado'], [1, 'No respaldado']]),
        ),
    ]
