# Generated by Django 4.2.7 on 2023-11-25 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_detalle_backup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_backup',
            name='id_backup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup', to='proyecto.backup'),
        ),
    ]
