# Generated by Django 4.2.7 on 2023-11-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_detalle_backup_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_backup',
            name='contenido',
            field=models.FileField(upload_to='respaldos/'),
        ),
    ]
