# Generated by Django 4.2.7 on 2023-11-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_detalle_backup_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_backup',
            name='contenido',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
