# Generated by Django 4.2.7 on 2023-11-25 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_alter_detalle_backup_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_backup',
            name='id_backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup', to='proyecto.backup'),
        ),
        migrations.AlterField(
            model_name='detalle_backup',
            name='registro',
            field=models.TextField(blank=True),
        ),
    ]
