# Generated by Django 4.2.7 on 2024-02-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_alter_detalle_backup_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_backup',
            name='contenido',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
