# Generated by Django 4.2.7 on 2024-02-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_alter_detalle_backup_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.CharField(default='*', max_length=20)),
                ('hora', models.CharField(default='*', max_length=20)),
                ('dia_mes', models.CharField(default='*', max_length=20)),
                ('mes', models.CharField(default='*', max_length=20)),
                ('dia_semana', models.CharField(default='*', max_length=20)),
            ],
        ),
    ]
