# Generated by Django 4.2.7 on 2024-02-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_remove_cronconfig_dia_mes_remove_cronconfig_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('dia', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CronConfig',
        ),
    ]
