# Generated by Django 4.2.7 on 2024-02-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_programaciontarea_delete_cronconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramacionTarea',
        ),
    ]
