# Generated by Django 4.2.7 on 2024-03-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_delete_programaciontarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.CharField(max_length=2)),
                ('hora', models.CharField(max_length=2)),
                ('dia_mes', models.CharField(max_length=2)),
                ('mes', models.CharField(max_length=2)),
                ('dia_semana', models.CharField(max_length=2)),
            ],
        ),
    ]
