# Generated by Django 4.2.7 on 2024-03-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_configuracion_delete_tareaprogramada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
