# Generated by Django 4.2.7 on 2024-03-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_delete_configuracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.CharField(max_length=50)),
                ('horas', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
                ('dia_semana', models.CharField(max_length=50)),
            ],
        ),
    ]
