# Generated by Django 4.2.7 on 2024-03-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_programaciontarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
                ('dia_semana', models.CharField(max_length=50)),
                ('comando', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ProgramacionTarea',
        ),
    ]
