# Generated by Django 4.2.7 on 2024-03-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_tareaprogramada_delete_programaciontarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaprogramada',
            name='comando',
        ),
    ]
