# Generated by Django 4.2.7 on 2024-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0020_remove_tareaprogramada_comando'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='name_history',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
