# Generated by Django 4.2.7 on 2024-03-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0021_backup_name_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='name_history',
        ),
    ]
